Add support for proFPGA XCVU19P board
litex-hub/litex-boards pull request #125
Opened 2020-11-23 15:38 UTC by piotr-binkowski

This PR aims to add support for proFPGA XCVU19P board (https://www.profpga.com/profpga-xcvu19p).
Before merging serial port configuration needs to be adjusted since current pins are connected to onboard LEDs (and it looks like this board has no onboard USB-UART converter).
@enjoy-digital what would be the best way to handle UART in this case?
Is is possible to disable it entirely or maybe configure it to be accessible via PCIe-Wishbone bridge?

Also this platform represents only one configuration of this board (FPGA board with PCIe adapter attached to port TA1) but in theory many more modules can be attached to different expansion ports so I'm wondering if there is a better way to represent such configurations in Litex?

2020-11-23 16:09 UTC, enjoy-digital requested changes
Thanks @piotr-binkowski,

- for the serial, you can remove it and just force the uart to `crossover` (kwargs["uart_name"] = crossover).
- for the PCIe/Connector, you should probably create connectors for the different connectors of the boards (ex: https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/arty.py#L158) and then create functions for the adapter you can plug on a connector, ass done for example here: https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/arty.py#L285-L307.
- for LitePCIe, can you use the new LiteX's add_pcie method to simplify the integration: https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/xcu1525.py#L93-L99

Thanks

2020-11-23 20:43 UTC, mithro commented
FYI - The person writing this is @piotr-binkowski not @esden :-P -- Too many Piotr's I think :-)

2020-11-23 21:21 UTC, enjoy-digital commented
Ah sorry, i was aware i was answering to @piotr-binkowski but auto-completion probably suggested the wrong Piotr...

2020-12-01 09:20 UTC, enjoy-digital commented
@piotr-binkowski, @mithro: after thinking a bit about it, I don't think it's a good idea to integrate this proFPGA VU19P: most of the boards used in LiteX and the ecosystem have been selected to be useful and affordable to allow others to reproduce results. The Ultrascale boards are still expensive but I tried to select affordable ones (BCU1525 and FK33 that can be found around 1k$), which still allow some users of the community to buy them and play with them. Here with the proFPGA VU19P we are probably around 70k$ the board (and probably more), so this is only accessible to very large companies.

I'm already using proFPGA boards for some clients and testing the cores on them, but maintain them in specific repositories. So this configuration should probably be supported and maintained in a specific project/repository. The current Ultrascale(+) code is also working, but some refactoring is needed to ease supporting more boards, for example: #42. So let's first finish things that have been started before going further.

2020-12-01 17:43 UTC, mithro commented
@enjoy-digital - I don't see any reason to not have all boards which people are using in this repo? Otherwise multiple people will be writing these and getting them wrong.

2020-12-01 17:54 UTC, mithro commented
Just like Linux supports extremely large 100 CPUs IBM, $100k USD, systems and tiny little 1 core, $10 USD RPi Zero systems, everyone benefits by working together and sharing their work in common place. 

Also, yesterday's $10k USD system is tomorrow's $1k USD system. Today, the $35 USD RPi is a Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz beast, while the first RPi had a single-core 700MHz CPU :-).

2020-12-01 21:17 UTC, enjoy-digital commented
The proFPGA boards are not classical FPGA board similar to ones supported in LiteX-boards but prototyping systems. They are basically just FPGAs exposing IOs on connectors and that you can customize by adding mezzanine adapter boards. So to support them correctly, for each prototyping system, you need to create a platform file, then create the adapter files (for the different mezzanines that you can plug on it) that you can reuse between platforms and then example targets for the different possible configurations (with PCIe mezzanine, DDR4 mezzanine, etc....) So in addition to being very expensive, correctly supporting these boards is a whole project by itself.

So this is not the aim of this repository. Creating an external project for proFPGA boards with plarforms/adapters/examples could be interesting, but I don't have the resources/time to maintain it.

2020-12-01 21:17 UTC, closed without merging

2020-12-02 12:09 UTC, enjoy-digital commented
@piotr-binkowski, @mithro: the work from this PR and from https://github.com/enjoy-digital/litepcie/pull/44 has been integrated in https://github.com/litex-hub/litex-on-profpga-systems with additional simplifications and features. I'll go a bit further after lunch but we can continue the discussion here if you want. I'm just trying to create a skeleton to ease supporting proFPGA boards, this could be used for this PoC, and could be extended later if more proFPGA boards are supported but I don't think I'll have the time/ressources to maintain it.

2020-12-03 10:14 UTC, enjoy-digital commented
https://github.com/litex-hub/litex-on-profpga-systems has been updated with an initial attempt to implement the ideas described in the previous comments. I also listed ideas in issues that I think could be interesting to implement if we want to explore more with proFPGA boards and LiteX. 

Sorry if closing the issue has been miss-interpreted, I was doing a bunch of update on issues/PR of the project and maybe closed this one to fast. I'll be more careful in the future but would also like similar PRs to this be discussed in issues first, from a maintainer point of view I find easier to say say no to an idea in an issue than in a PR since I'm well aware that some work has already been done in the PR and closing it could generate frustration.

Anyway, leaving aside these integration aspects, I'm very happy to see LitePCIe validated and used on such hardware.